project:
  type: website

website:
  title: "James' Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/james4ever0
format:
  html:
    theme: cosmo
    css: styles.css



