---
{"categories": &id001 ["artificial intelligence", "AGI", "AI playground", "interfaces", "terminal", "GUI", "API"], "category": "AI development", "date": "2022-10-16 14:30:53", "description": "This article delves into the topic of artificial general intelligence (AGI) and proposes establishing an AI model training playground. It stresses the significance of utilizing diverse interfaces, such as terminal, GUI, API, and network, for effective AGI development. The author shares their background in AGI research, including projects like AGI, lazero, metalazero, NSJail with Docker, and Firejail.", "tags": *id001, "title": "AGI playground, a place for AGI to act/code freely"}

---

------
search for "artificial general intelligence" in github and hit many results.
some article says deep neural networks are t2 level, human are t3 level (connected dnns) and to train a t3 level intel you need t4 level intel (like the earth, or a group of t3 intels, you can't be 1-to-1 now, you must be forgiving). this proves my provision of putting agi into gui or human interfaces.
to train a t2 level intel, you need t3 intel, such as yourself or your users.
you must setup this playground then you begin to learn stuff and libraries of AGI. but once you have one, don't move around, stick to it! you need time to develop the general adaptor and make clear and achievable goals!
terminal, GUI, program, API, network
please check my previous efforts on building AGI, namely: AGI, lazero, metalazero
[nsjail](https://nsjail.dev/) with docker
firejail
