---
{"categories": &id001 ["AGI", "finance", "financial", "quantatitive trading", "schedule", "stock"], "category": "Artificial General Intelligence", "date": "2023-12-22 23:52:59", "description": "This personal study plan covers various topics including reviewing past notes, revisiting history, studying finance and quantitative trading, and exploring artificial general intelligence. Tasks involved range from completing unfinished notes to designing algorithms and executing shell commands.", "tags": *id001, "title": "self-learning schedules"}

---

------

# self-learning schedules

## review previous notes and fill blanks, list blanks below, better with direct link to it
- [x] tag all notes, especially mark out those stub, incomplete ones
- [ ] review and complete bilibili courses, reorder, rename and split them if necessary
- [ ] 传播学导论把笔记做完

## review your history
- [ ] visit all previously visited links and store briefs generated by readbility.js and elinks

## finance and quantatitive trading
- [x] design a basic algorithm and complete regression test on joinquant
- [ ] design and complete one regression test offline

## artificial general intelligence
- [ ] design a program automatically execute commands in shell
- [ ] design a program automatically click everywhere in GUI
### study nars
- [ ] run python version of nars
### study opencog
### study he4o

