---
{"categories": &id001 ["mini-ITX computer", "Mac Studio comparison", "cost efficiency", "power consumption", "hardware options", "cooling solutions", "case design"], "category": "Mini-ITX Computers", "date": "2023-12-22 23:52:59", "description": "This article compares the cost, power consumption, and hardware options between a mini-ITX computer with high RAM capacity and Apple's Mac Studio. The discussion covers cooling solutions and case design to prevent overheating.", "tags": *id001, "title": "mini server, portable server, itx, Mac studio"}

---

------

# mini server, portable server, itx, Mac studio

says that the cost of building some mini-itx with enormous ram costs a lot (more than te mac studio), and with a lot of headaches with custom designing, cnc and stl. worth it?

also the power consumption will be higher than mac studio.

assemble the machine with proper thermo, wires and some open space, then enclose the thing with design.


the weight:

mac studio (m1 ultra) for 3.6kg 

mini-itx machine: 6.3 kg - 10 kg (won't lose weight)

## graphic cards

a100 80g
a16 64g (with self-designed thermal solution)

## mother boards

Asrock X299e-itx using 4 mini ram slots

ASROCK X570D4I-2T

AsRock Rack E3C246D4I-2T Mini-ITX Server Motherboard Intel LGA 1151 C246, (max ram: 128gb)

ROMED4ID-2T for amd epyc 7002

asrock C422 WSI/IPMI

## thermo solutions

generally you need to design case, thermo yourself, to make both side covered

use metal first. do not use plastic in case of overheating and burning

### cpu

corsair h5 sf (hydra)

### gpu

a100 thermo mod for hydra

